### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ReLexioN** [rodel77/MiniBoardGames#10] opened 2017-05-20 08:17 UTC
Spigot 1.8.8 java 8 error on startup:
[11:08:43 WARN]: org.apache.commons.lang.UnhandledException: Plugin MiniBoardGames v2.9.0 generated an exception while executing task 48
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
at mx.com.rodel.MBG$1.run(MBG.java:228)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
... 3 more

**Comment by rodel77** [comment] 2017-05-21 00:36
Thanks for report it i will check it soon!

**Comment by rodel77** [comment] 2017-05-21 00:47
I check it and its API error, can you send me a message from Spigot with your ID?

**Comment by bertek41** [comment] 2017-05-21 11:21
Same problem for me.
`[14:16:44] [Craft Scheduler Thread - 44/WARN]: Exception in thread "Craft Scheduler Thread - 44" 
[14:16:44] [Craft Scheduler Thread - 44/WARN]: org.apache.commons.lang.UnhandledException: Plugin MiniBoardGames v2.9.1 generated an exception while executing task 48
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at mx.com.rodel.MBG$1.run(MBG.java:228)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more`

**Comment by rodel77** [comment] 2017-05-23 00:53
Hello please do what i say in past reply:

> I check it and its API error, can you send me a message from Spigot with your ID?

**Comment by rodel77** [comment] 2017-05-24 08:04
Last chance, if you don't follow my instructions i will close the issue! @ReLexioN 

> I check it and its API error, can you send me a message from Spigot with your ID?

**Comment by rodel77** [comment] 2017-05-25 05:19
Closed for lack of info!

**Closed as completed by rodel77** 2017-05-25 05:19 UTC
Labels: wontfix
